require_relative '../simplecov_custom_profiles'
SimpleCov.start 'refried'
require 'rspec/support/spec'
# require 'factory_girl'
# require_relative 'support/factory_girl'
require_relative '../lib/refried'